# Generated by Django 2.2 on 2019-06-26 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
