# Generated by Django 2.2 on 2019-06-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
